spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth_example
    username: root
    password: Alex@1386
com:
  schlader:
    james:
      cors-origin: http://localhost:3000
server:
  port: 8088


